server:
  port: 8888
  ssl:
    enabled: true
    key-store: C:\\ssl\\server.p12
    key-store-password: QWas!@34
    key-store-type: PKCS12

spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user:
      name: root
      password: rootpassword
  cloud:
    config:
      server:
        git:
          uri: https://github.com/E-HAS/SpringBoot-MSA-Config-Repo
          default-label: main
          skipSslValidation: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  Prometheus:
    metrics:
      export:
        enabled: true

value:
  security:
    allow-ip-list: 127.0.0.1, 192.168.1.128, 192.168.1.101, 192.168.1.102